trigger:
- '*'

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'BUILD'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-16.04'
      demands:
        - npm

    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      dotnetSdkVersion: '3.1.100'

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'

    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false

    - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
      displayName: 'Compile Sass assets'

    - task: gulp@1
      displayName: 'Run gulp tasks'

    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: $(wwwrootDir)

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project for $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Publish project for $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

  - job: BuildDacpac
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: VSBuild@1
      displayName: 'Build database project. Generate .dacpac file'
      inputs:
        project: '**/*.sqlproj'

    - task: CopyFiles@2
      displayName: 'Copy .dacpac file to staging directory'
      inputs:
        contents: |
          Tailspin.SpaceGame.Database/bin/**/*.dacpac
        targetFolder: '$(Build.StagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish .dacpac Artifact to Pipeline'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: dropDacpac
      condition: succeededOrFailed()

- stage: DB_VERIFY
  displayName: 'Verify database schema changes (DB VERIFY)'
  dependsOn: BUILD
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-2019'
    variables:
    - group: 'Release'
    environment: 'DB_VERIFY'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: dropDacpac
            patterns: '**/*'

          - task: SqlAzureDacpacDeployment@1
            displayName: Generate schema change script (SQLDelta.sql)
            inputs:
              azureSubscription: 'azAppServiceCon'
              authenticationType: 'server'
              serverName: '$(dbServerName).database.windows.net'
              databaseName: '$(dbName)'
              sqlUsername: '$(dbAdminLogin)'
              sqlPassword: '$(dbAdminPassword)'
              deployType: 'DacpacTask'
              deploymentAction: 'Script'
              dacpacFile: '$(Pipeline.Workspace)/dropDacpac/Tailspin.SpaceGame.Database/bin/Debug/Tailspin.SpaceGame.Database.dacpac'
              ipDetectionMethod: 'AutoDetect'

          - task: PowerShell@2
            displayName: Show Generated SQL Script (SQLDelta.sql)
            inputs:
              targetType: 'inline'
              script: | 
                Write-Host "Auto Generated SQL Update Script:"
                Get-Content d:\a\1\s\GeneratedOutputFiles\$(dbName)_Script.sql | foreach {Write-Output $_}
          
          - task: PowerShell@2
            displayName: 'Check for Schema Changes. Add/Set "SchemaChanged" Pipeline Variable'
            inputs:
              targetType: 'inline'
              script: |
                # Print the schema change script
                Write-Host "Auto Generated SQL Update Script:"
                Get-Content d:\a\1\s\GeneratedOutputFiles\$(dbName)_Script.sql | foreach {Write-Output $_}

                # Check for schema changes
                $file = Get-Content "d:\a\1\s\GeneratedOutputFiles\$(dbName)_Script.sql"
                $containsWord = $file | %{$_ -match "CREATE" -or $_ -match "ALTER" -or $_ -match "DROP"}
                if ($containsWord -contains $true) {
                  Install-Module VSTeam -Scope CurrentUser -Force
                  Set-VSTeamAccount –Account $(Acct) -PersonalAccessToken $(PAT)
                  $methodParameters = @{
                    ProjectName = "$(System.TeamProject)"
                    Name = "Release"}
                  $vg = Get-VSTeamVariableGroup @methodParameters
                  $vars = @{}
                  $vg.variables | Get-Member -MemberType *Property | %{$vars.($_.Name) = $vg.variables.($_.Name)}
                  $varName = "schemaChanged"
                  $vars.$varName= @{}
                  $vars.$varName.value = "True"
                  $vars.$varName.isSecret = $false
                  $methodParameters = @{
                    id = $vg.id
                    ProjectName = "$(System.TeamProject)"
                    Name = "Release"
                    Description = ""
                    Type = "Vsts"
                    Variables = $vars}
                  Update-VSTeamVariableGroup @methodParameters}

- stage: DB_APPLY
  variables:
    - group: 'Release'
  displayName: 'Apply database schema changes (DB APPLY)'
  dependsOn: DB_VERIFY
  condition: |
    and
    (
      succeeded('DB_VERIFY'),
      eq(variables['schemaChanged'],True)
    )
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-2019'
    variables:
    - group: 'Release'
    environment: 'DB_APPLY'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: dropDacpac
            patterns: '**/*'

          - task: SqlAzureDacpacDeployment@1
            displayName: 'Generate Deploy SQL schema (SQLDelta.sql) to Pipeline'
            inputs:
              azureSubscription: 'azAppServiceCon'
              authenticationType: 'server'
              serverName: '$(dbServerName).database.windows.net'
              databaseName: '$(dbName)'
              sqlUsername: '$(dbAdminLogin)'
              sqlPassword: '$(dbAdminPassword)'
              deployType: 'DacpacTask'
              deploymentAction: 'Publish'
              dacpacFile: '$(Pipeline.Workspace)/dropDacpac/Tailspin.SpaceGame.Database/bin/Debug/Tailspin.SpaceGame.Database.dacpac'
              ipDetectionMethod: 'AutoDetect'

          - task: PowerShell@2
            displayName: 'Remove "SchemaChanged Pipeline Variable. Clean up"'
            inputs:
              targetType: 'inline'
              script: |
                Install-Module VSTeam -Scope CurrentUser -Force
                Set-VSTeamAccount –Account $(Acct) -PersonalAccessToken $(PAT)
                $methodParameters = @{
                  ProjectName = "$(System.TeamProject)"
                  Name = "Release"}
                $vg = Get-VSTeamVariableGroup  @methodParameters 
                $vars = @{}
                $vg.variables | Get-Member -MemberType *Property | %{$vars.($_.Name) = $vg.variables.($_.Name)}
                $vars.Remove("schemaChanged")
                $methodParameters = @{
                  id = $vg.id
                  ProjectName = "$(System.TeamProject)"
                  Name = "Release"
                  Description = ""
                  Type = "Vsts"
                  Variables = $vars}
                Update-VSTeamVariableGroup @methodParameters

- stage: 'DEV'
  displayName: 'Deploy to DEV'
  dependsOn: 
    - DB_VERIFY
    - DB_APPLY
  condition: |
    and
    (
      succeeded('DB_VERIFY'),
      in(dependencies.DB_VERIFY.result,'Succeeded','Skipped')
    )
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-16.04'
    environment: DEV
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website (DEV)'
            inputs:
              azureSubscription: 'azAppServiceCon'
              appName: '$(WebAppNameDev)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'

- stage: 'QA'
  displayName: 'Deploy to QA'
  dependsOn: DEV
  condition: succeeded()
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-16.04'
    environment: QA
    variables:
    - group: 'Release'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website (QA)'
            inputs:
              azureSubscription: 'azAppServiceCon'
              appName: '$(WebAppNameQA)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'

- stage: 'STAGING'
  displayName: 'Deploy to STAGING'
  dependsOn: QA
  condition: succeeded() 
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-16.04'
    environment: STAGING
    variables:
    - group: 'Release'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website (STAGING)'
            inputs:
              azureSubscription: 'azAppServiceCon'
              appName: '$(WebAppNameStaging)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
